replicaCount: 1

image:
  tag: "25.2.0.102705-community"

edition: ""
community:
  enabled: true

service:
  type: LoadBalancer
  port: 9000

resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "2"
    memory: "4Gi"

persistence:
  enabled: true
  storageClass: "gp2-immediate"
  size: "4Gi"

postgresql:
  enabled: true
  postgresqlUsername: "sonarUser"
  postgresqlPassword: "sonarPass"
  postgresqlDatabase: "sonarDB"

monitoringPasscodeSecretName: "sonar-monitoring-passcode"
monitoringPasscodeSecretKey: "myStrongPasscode123"